### ISSUE TITLE
sudo required to write log

### ISSUE THREAD

**Issue by 7yl4r** [7yl4r/backdat#14]
Even when just getting status, backdat wants to write to its log file (usually 644 owned by root) and needs to stat all backed up files anyway so the following error is thrown:

```
tylar@tylardesk:~$ ls -lh /var/opt/backdat/backdat.log
-rw-r--r-- 1 root root 239K Sep 27 21:30 /var/opt/backdat/backdat.log

tylar@tylardesk:~$ /opt/backdat/backdat.py status --max_period

Traceback (most recent call last):
  File "/opt/backdat/backdat.py", line 75, in <module>
    '/var/opt/backdat/backdat.log', maxBytes=1e6, backupCount=5
  File "/usr/lib/python3.5/logging/handlers.py", line 150, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.5/logging/handlers.py", line 57, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.5/logging/__init__.py", line 1008, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.5/logging/__init__.py", line 1037, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/var/opt/backdat/backdat.log'
```

**Comment by 7yl4r** [comment]
One workaround is to grant telegraf user sudo for backdat. Something like:

```
#   ensure telegraf can execute w/ sudo  (TODO: set this up w/ https://forge.puppet.com/saz/sudo )
      sudo visudo
        # User privilege specification
        root    ALL=(ALL:ALL) ALL
        telegraf        ALL=(ALL)       NOPASSWD:       /opt/backdat/backdat.py status --max_period
```
