### ISSUE TITLE
missing post-backup events following pre-backup?

### ISSUE THREAD

**Issue by 7yl4r** [7yl4r/backdat#15]
For some reason all VMs on manglillo were paused this morning.
backdat is the only possible culprit that comes to mind.
gdrive_backuper should now be fully removed.

Looking through logs didn't reveal much, but I didn't see any backdat logs (curious :thinking:).

There are no running backdat or rclone processes. 

Not sure why the post-backup didn't get called.

**Comment by 7yl4r** [comment]
```
[root@manglillo ~]# cat /etc/cron.d/backdat 
# this file auto-generated by backdat.
00 03 * * *  root /usr/bin/flock -n /tmp/backdat.lockfile /opt/backdat/backdat.py
```

The lockfile is still in place; more evidence that backdat failed & didn't run the `finally` post-backdat block.

```
[root@manglillo ~]# ls -lh /tmp/backdat.lockfile 
-rw-r--r--. 1 root root 0 Nov 20 22:00 /tmp/backdat.lockfile
```

**Comment by 7yl4r** [comment]
Ah... I see what's going on here.
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/backdat/backdat/BackupManager.py", line 79, in do_next_backup
    rclone.backup(self.next_backup_args)
  File "/opt/backdat/backdat/RemoteInterface/rclone.py", line 75, in backup
    wrapped_command=build_rclone_cmd(args)
  File "/opt/backdat/backdat/ProcessWrapHandler.py", line 56, in execute
    self.logger.debug(res_stdout)
UnboundLocalError: local variable 'res_stdout' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.4/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib64/python3.4/logging/handlers.py", line 187, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib64/python3.4/logging/__init__.py", line 828, in format
    return fmt.format(record)
  File "/usr/lib64/python3.4/logging/__init__.py", line 565, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.4/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/opt/backdat/backdat.py", line 106, in <module>
    args.func(args)
  File "/opt/backdat/backdat/main.py", line 10, in backup
    backman.start_backups()
  File "/opt/backdat/backdat/BackupManager.py", line 54, in start_backups
    self.do_next_backup()
  File "/opt/backdat/backdat/BackupManager.py", line 83, in do_next_backup
    self.logger.error("backup action failed!", err)
Message: 'backup action failed!'
Arguments: (UnboundLocalError("local variable 'res_stdout' referenced before assignment",),)
2018-11-26 15:04:54,509|WARNING	|BackupManager.py:59	|Finished all backups with time to spare!
```
