### ISSUE TITLE
status w/ nonexistent file throws error

### ISSUE THREAD

**Issue by 7yl4r** [7yl4r/backdat#16]
```
[root@thing2 thing2]# sudo /opt/backdat/backdat.py status --max_period
Traceback (most recent call last):
  File "/opt/backdat/backdat.py", line 106, in <module>
    args.func(args)
  File "/opt/backdat/backdat/main.py", line 14, in status
    print(assess_max_period())
  File "/opt/backdat/backdat/assessments.py", line 87, in assess_max_period
    return round(backup_history.get_backup_period_max(3))
  File "/opt/backdat/backdat/file_parsers/backup_history.py", line 109, in get_backup_period_max
    avg_t, min_t, max_t = get_backup_period_stats(n_backups_to_check)
  File "/opt/backdat/backdat/file_parsers/backup_history.py", line 123, in get_backup_period_stats
    for fstat in get_fileset_statlist(): # TODO: maybe do just a few of them to save time
  File "/opt/backdat/backdat/file_parsers/fileset.py", line 74, in get_fileset_statlist
    size = os.stat(src_filename).st_size  # in Bytes [B]
FileNotFoundError: [Errno 2] No such file or directory: '/thing2/imars-objects/gom:'
```

`gom` was moved off this server and I forgot to remove it from the fileset.

In that sense the error is correct, but the status subcommand should handle this better.
One missing file kills the whole report and breaks the metrics in `metrics.sh`.

Workaround is of course to remove nonexistent files from the `fileset.csv`.

**Comment by 7yl4r** [comment]
Oh, maybe this is a more serious bug than I thought:

```
[root@thing2 thing2]# sudo /opt/backdat/backdat.py status --max_period
Traceback (most recent call last):
  File "/opt/backdat/backdat.py", line 106, in <module>
    args.func(args)
  File "/opt/backdat/backdat/main.py", line 14, in status
    print(assess_max_period())
  File "/opt/backdat/backdat/assessments.py", line 87, in assess_max_period
    return round(backup_history.get_backup_period_max(3))
  File "/opt/backdat/backdat/file_parsers/backup_history.py", line 109, in get_backup_period_max
    avg_t, min_t, max_t = get_backup_period_stats(n_backups_to_check)
  File "/opt/backdat/backdat/file_parsers/backup_history.py", line 123, in get_backup_period_stats
    for fstat in get_fileset_statlist(): # TODO: maybe do just a few of them to save time
  File "/opt/backdat/backdat/file_parsers/fileset.py", line 74, in get_fileset_statlist
    size = os.stat(src_filename).st_size  # in Bytes [B]
FileNotFoundError: [Errno 2] No such file or directory: '/thing2/imars-objects/installers:'
[root@thing2 thing2]# ls -lah /thing2/imars-objects/installers/
total 23G
drwxrwxrwx.  3 root            imars-common 4.0K May 24  2018 .
drwxr-xr-x. 51 imars-data-user imars-common 4.0K Jan 14 17:23 ..
-rw-r--r--.  1 root            root          11G May 23  2018 matlab_R2017b.tar.bz2
drwxr-xr-x. 10 root            root         4.0K May 24  2018 matlab_R2018a
-rw-rw-r--.  1            1000         1000 7.0G May 24  2018 R2018a_Linux64_dvd1.iso
-rw-rw-r--.  1            1000         1000 5.0G May 24  2018 R2018a_Linux64_dvd2.iso
```

Currently thing2 has not WAN connectivity. Not sure how that might be related, but little else has changed.

_edit: still seeing the problem after WAN issue resolved. This issue is potentially older than expected._
