### ISSUE TITLE
how to deal with failed backups?

### ISSUE THREAD

**Issue by 7yl4r** [7yl4r/backdat#8]
Got this traceback from trying to back up a file that no longer exists:

```
Traceback (most recent call last):
  File "/opt/backdat/backdat.py", line 88, in <module>
    args.func(args)
  File "/opt/backdat/backdat/main.py", line 8, in backup
    backman.start_backups()
  File "/opt/backdat/backdat/BackupManager.py", line 54, in start_backups
    self.do_next_backup()
  File "/opt/backdat/backdat/BackupManager.py", line 78, in do_next_backup
    rclone.backup(self.next_backup_args)
  File "/opt/backdat/backdat/RemoteInterface/rclone.py", line 83, in backup
    raise sub_err
  File "/opt/backdat/backdat/RemoteInterface/rclone.py", line 76, in backup
    universal_newlines=True
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['rclone', '--modify-window', '24h', '--config', '/var/opt/backdat/rclone.conf', '--log-level', 'INFO', 'sync', '/mnt/RAID/imars-objects/ftp-ingest/testfile', 'gdrive-ty:/IMARS/backups/backdat/thing3/mnt/RAID/imars-objects/ftp-ingest']' returned non-zero exit status 1
```

This failure means that the file never gets removed from the backup-plan and thus backdat gets stuck in a loop failing on this indefinitely, which is certainly not best. However, quietly skipping over failures might not be ideal either. So how should failures be dealt with?

**Comment by 7yl4r** [comment]
That metric along with the `check` subcommand for closer inspection ought to cover any use cases I guess.

![image](https://user-images.githubusercontent.com/1051390/35123070-c54c87d8-fc98-11e7-9743-f305771c2087.png)
